apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-service
  namespace: gke-yolo-namespace
spec:
  selector:
    matchLabels:
      app: yolo-service
  template:
    metadata:
      labels:
        app: yolo-service
    spec:
      containers:
        - name: yolo-container
          image: gcr.io/final-project-453122/yolo-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: TRITON_URL
              value: "http://triton-service.gke-yolo-namespace.svc.cluster.local:8000"

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: yolo-hpa
  namespace: gke-yolo-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yolo-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
