apiVersion: v1
kind: Service
metadata:
  name: yolo-service
  namespace: gke-yolo-namespace
spec:
  selector:
    app: yolo-service
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
